services:
    api:
        container_name: country_api
        build:
            context: src
            dockerfile: Country.Api/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_HTTP_PORTS=5000 
        ports:
            - "7200:5000"
    jaeger:
        container_name: jaeger_countryapp
        ports:
            - "16686:16686"

        