name: "country-app"

services:
    api:
        image: ${DOCKER_REGISTRY-}country-api
    jaeger:
        image: jaegertracing/all-in-one:1.58.0
    prometheus:
        image: prom/prometheus:v3.1.0
    grafana:
        image: grafana/grafana:11.4.0-ubuntu