services:
    api:
        container_name: country_api
        build:
            context: src
            dockerfile: Country.Api/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_HTTP_PORTS=5000 
        ports:
            - "7200:5000"

    jaeger:
        container_name: jaeger_countryapp
        ports:
            - "16686:16686"

    prometheus:
        container_name: prometheus_countryapp
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'

    grafana:
        container_name: grafana_countryapp
        ports:
            - "3000:3000"
        volumes:
            - 'grafana_storage:/var/lib/grafana'
            - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
        environment:
            GF_AUTH_ANONYMOUS_ENABLED: "true"
            GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"

    otel-collector:
        container_name: collector_countryapp
        volumes:
            - ./otel-collector-config.yml:/etc/otel/config.yaml
            - ./log:/log/otel
        command: --config /etc/otel/config.yaml
        environment:
            JAEGER_ENDPOINT: "jaeger:4317"
        ports:
            - "8889:8889" # Prometheus metrics exporter (scrape endpoint)
            - "13133:13133" # health check extension
            - "55679:55679" # ZPages extension
            - "4317:4317" # OTLP receiver 
        depends_on:
            - jaeger
            - prometheus 

volumes:
    grafana_storage:

        