services:
    api:
        container_name: country_api
        build:
            context: src
            dockerfile: Country.Api/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_HTTP_PORTS=5000 
        ports:
            - "7200:5000"
    jaeger:
        container_name: jaeger_countryapp
        ports:
            - "16686:16686"
    prometheus:
        container_name: prometheus_countryapp
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
    grafana:
        container_name: grafana_countryapp
        ports:
            - "3000:3000"
        volumes:
            - 'grafana_storage:/var/lib/grafana'
            - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
        environment:
            GF_AUTH_ANONYMOUS_ENABLED: "true"
            GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"

volumes:
    grafana_storage:

        